// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/exposed.proto

package com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto;

public final class Exposed {
  private Exposed() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoExposedListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 batchReleaseTime = 1;</code>
     * @return The batchReleaseTime.
     */
    long getBatchReleaseTime();

    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> 
        getExposedList();
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getExposed(int index);
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    int getExposedCount();
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    java.util.List<? extends com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder> 
        getExposedOrBuilderList();
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder getExposedOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList}
   */
  public static final class ProtoExposedList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList)
      ProtoExposedListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoExposedList.newBuilder() to construct.
    private ProtoExposedList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoExposedList() {
      exposed_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoExposedList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoExposedList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              batchReleaseTime_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                exposed_ = new java.util.ArrayList<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee>();
                mutable_bitField0_ |= 0x00000001;
              }
              exposed_.add(
                  input.readMessage(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          exposed_ = java.util.Collections.unmodifiableList(exposed_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.class, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.Builder.class);
    }

    public static final int BATCHRELEASETIME_FIELD_NUMBER = 1;
    private long batchReleaseTime_;
    /**
     * <code>int64 batchReleaseTime = 1;</code>
     * @return The batchReleaseTime.
     */
    @java.lang.Override
    public long getBatchReleaseTime() {
      return batchReleaseTime_;
    }

    public static final int EXPOSED_FIELD_NUMBER = 2;
    private java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> exposed_;
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> getExposedList() {
      return exposed_;
    }
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder> 
        getExposedOrBuilderList() {
      return exposed_;
    }
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    @java.lang.Override
    public int getExposedCount() {
      return exposed_.size();
    }
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    @java.lang.Override
    public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getExposed(int index) {
      return exposed_.get(index);
    }
    /**
     * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
     */
    @java.lang.Override
    public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder getExposedOrBuilder(
        int index) {
      return exposed_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (batchReleaseTime_ != 0L) {
        output.writeInt64(1, batchReleaseTime_);
      }
      for (int i = 0; i < exposed_.size(); i++) {
        output.writeMessage(2, exposed_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (batchReleaseTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, batchReleaseTime_);
      }
      for (int i = 0; i < exposed_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, exposed_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList)) {
        return super.equals(obj);
      }
      com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList other = (com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList) obj;

      if (getBatchReleaseTime()
          != other.getBatchReleaseTime()) return false;
      if (!getExposedList()
          .equals(other.getExposedList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BATCHRELEASETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBatchReleaseTime());
      if (getExposedCount() > 0) {
        hash = (37 * hash) + EXPOSED_FIELD_NUMBER;
        hash = (53 * hash) + getExposedList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList)
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.class, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.Builder.class);
      }

      // Construct using com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExposedFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        batchReleaseTime_ = 0L;

        if (exposedBuilder_ == null) {
          exposed_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          exposedBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor;
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList getDefaultInstanceForType() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.getDefaultInstance();
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList build() {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList buildPartial() {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList result = new com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList(this);
        int from_bitField0_ = bitField0_;
        result.batchReleaseTime_ = batchReleaseTime_;
        if (exposedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            exposed_ = java.util.Collections.unmodifiableList(exposed_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.exposed_ = exposed_;
        } else {
          result.exposed_ = exposedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList) {
          return mergeFrom((com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList other) {
        if (other == com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList.getDefaultInstance()) return this;
        if (other.getBatchReleaseTime() != 0L) {
          setBatchReleaseTime(other.getBatchReleaseTime());
        }
        if (exposedBuilder_ == null) {
          if (!other.exposed_.isEmpty()) {
            if (exposed_.isEmpty()) {
              exposed_ = other.exposed_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExposedIsMutable();
              exposed_.addAll(other.exposed_);
            }
            onChanged();
          }
        } else {
          if (!other.exposed_.isEmpty()) {
            if (exposedBuilder_.isEmpty()) {
              exposedBuilder_.dispose();
              exposedBuilder_ = null;
              exposed_ = other.exposed_;
              bitField0_ = (bitField0_ & ~0x00000001);
              exposedBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExposedFieldBuilder() : null;
            } else {
              exposedBuilder_.addAllMessages(other.exposed_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long batchReleaseTime_ ;
      /**
       * <code>int64 batchReleaseTime = 1;</code>
       * @return The batchReleaseTime.
       */
      @java.lang.Override
      public long getBatchReleaseTime() {
        return batchReleaseTime_;
      }
      /**
       * <code>int64 batchReleaseTime = 1;</code>
       * @param value The batchReleaseTime to set.
       * @return This builder for chaining.
       */
      public Builder setBatchReleaseTime(long value) {
        
        batchReleaseTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 batchReleaseTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchReleaseTime() {
        
        batchReleaseTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> exposed_ =
        java.util.Collections.emptyList();
      private void ensureExposedIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          exposed_ = new java.util.ArrayList<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee>(exposed_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder> exposedBuilder_;

      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> getExposedList() {
        if (exposedBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exposed_);
        } else {
          return exposedBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public int getExposedCount() {
        if (exposedBuilder_ == null) {
          return exposed_.size();
        } else {
          return exposedBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getExposed(int index) {
        if (exposedBuilder_ == null) {
          return exposed_.get(index);
        } else {
          return exposedBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder setExposed(
          int index, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee value) {
        if (exposedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExposedIsMutable();
          exposed_.set(index, value);
          onChanged();
        } else {
          exposedBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder setExposed(
          int index, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder builderForValue) {
        if (exposedBuilder_ == null) {
          ensureExposedIsMutable();
          exposed_.set(index, builderForValue.build());
          onChanged();
        } else {
          exposedBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder addExposed(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee value) {
        if (exposedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExposedIsMutable();
          exposed_.add(value);
          onChanged();
        } else {
          exposedBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder addExposed(
          int index, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee value) {
        if (exposedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExposedIsMutable();
          exposed_.add(index, value);
          onChanged();
        } else {
          exposedBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder addExposed(
          com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder builderForValue) {
        if (exposedBuilder_ == null) {
          ensureExposedIsMutable();
          exposed_.add(builderForValue.build());
          onChanged();
        } else {
          exposedBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder addExposed(
          int index, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder builderForValue) {
        if (exposedBuilder_ == null) {
          ensureExposedIsMutable();
          exposed_.add(index, builderForValue.build());
          onChanged();
        } else {
          exposedBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder addAllExposed(
          java.lang.Iterable<? extends com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee> values) {
        if (exposedBuilder_ == null) {
          ensureExposedIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exposed_);
          onChanged();
        } else {
          exposedBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder clearExposed() {
        if (exposedBuilder_ == null) {
          exposed_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          exposedBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public Builder removeExposed(int index) {
        if (exposedBuilder_ == null) {
          ensureExposedIsMutable();
          exposed_.remove(index);
          onChanged();
        } else {
          exposedBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder getExposedBuilder(
          int index) {
        return getExposedFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder getExposedOrBuilder(
          int index) {
        if (exposedBuilder_ == null) {
          return exposed_.get(index);  } else {
          return exposedBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public java.util.List<? extends com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder> 
           getExposedOrBuilderList() {
        if (exposedBuilder_ != null) {
          return exposedBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exposed_);
        }
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder addExposedBuilder() {
        return getExposedFieldBuilder().addBuilder(
            com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.getDefaultInstance());
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder addExposedBuilder(
          int index) {
        return getExposedFieldBuilder().addBuilder(
            index, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.getDefaultInstance());
      }
      /**
       * <code>repeated .com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee exposed = 2;</code>
       */
      public java.util.List<com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder> 
           getExposedBuilderList() {
        return getExposedFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder> 
          getExposedFieldBuilder() {
        if (exposedBuilder_ == null) {
          exposedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder>(
                  exposed_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          exposed_ = null;
        }
        return exposedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList)
    }

    // @@protoc_insertion_point(class_scope:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposedList)
    private static final com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList();
    }

    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoExposedList>
        PARSER = new com.google.protobuf.AbstractParser<ProtoExposedList>() {
      @java.lang.Override
      public ProtoExposedList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoExposedList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoExposedList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoExposedList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposedList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoExposeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes key = 2;</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <code>int64 keyDate = 3;</code>
     * @return The keyDate.
     */
    long getKeyDate();
  }
  /**
   * Protobuf type {@code com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee}
   */
  public static final class ProtoExposee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee)
      ProtoExposeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoExposee.newBuilder() to construct.
    private ProtoExposee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoExposee() {
      key_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoExposee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoExposee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {

              key_ = input.readBytes();
              break;
            }
            case 24: {

              keyDate_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.class, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>bytes key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int KEYDATE_FIELD_NUMBER = 3;
    private long keyDate_;
    /**
     * <code>int64 keyDate = 3;</code>
     * @return The keyDate.
     */
    @java.lang.Override
    public long getKeyDate() {
      return keyDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!key_.isEmpty()) {
        output.writeBytes(2, key_);
      }
      if (keyDate_ != 0L) {
        output.writeInt64(3, keyDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, key_);
      }
      if (keyDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, keyDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee)) {
        return super.equals(obj);
      }
      com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee other = (com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (getKeyDate()
          != other.getKeyDate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + KEYDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKeyDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee)
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.class, com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.Builder.class);
      }

      // Construct using com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.ByteString.EMPTY;

        keyDate_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor;
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getDefaultInstanceForType() {
        return com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.getDefaultInstance();
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee build() {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee buildPartial() {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee result = new com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee(this);
        result.key_ = key_;
        result.keyDate_ = keyDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee) {
          return mergeFrom((com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee other) {
        if (other == com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee.getDefaultInstance()) return this;
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        if (other.getKeyDate() != 0L) {
          setKeyDate(other.getKeyDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes key = 2;</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>bytes key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private long keyDate_ ;
      /**
       * <code>int64 keyDate = 3;</code>
       * @return The keyDate.
       */
      @java.lang.Override
      public long getKeyDate() {
        return keyDate_;
      }
      /**
       * <code>int64 keyDate = 3;</code>
       * @param value The keyDate to set.
       * @return This builder for chaining.
       */
      public Builder setKeyDate(long value) {
        
        keyDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 keyDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyDate() {
        
        keyDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee)
    }

    // @@protoc_insertion_point(class_scope:com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.ProtoExposee)
    private static final com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee();
    }

    public static com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoExposee>
        PARSER = new com.google.protobuf.AbstractParser<ProtoExposee>() {
      @java.lang.Override
      public ProtoExposee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoExposee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoExposee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoExposee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.espol.asi_simulation.Backend_ASI_Simulation.Model.proto.Exposed.ProtoExposee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/exposed.proto\022;com.espol.asi" +
      "_simulation.Backend_ASI_Simulation.Model" +
      ".proto\"\210\001\n\020ProtoExposedList\022\030\n\020batchRele" +
      "aseTime\030\001 \001(\003\022Z\n\007exposed\030\002 \003(\0132I.com.esp" +
      "ol.asi_simulation.Backend_ASI_Simulation" +
      ".Model.proto.ProtoExposee\",\n\014ProtoExpose" +
      "e\022\013\n\003key\030\002 \001(\014\022\017\n\007keyDate\030\003 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposedList_descriptor,
        new java.lang.String[] { "BatchReleaseTime", "Exposed", });
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_espol_asi_simulation_Backend_ASI_Simulation_Model_proto_ProtoExposee_descriptor,
        new java.lang.String[] { "Key", "KeyDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
